### ISSUE TITLE
Account data exception for Christmas update

### ISSUE THREAD

**Issue by ArexNguyen** [GlennnM/FlashPrivateServer#4] opened 2023-12-20 00:10 UTC
The recent Christmas event broke my account, which I'm assuming is because I have a bunch of Christmas, Easter and Halloween items.
I can't log in, I get this error:
![Screenshot 2023-12-19 153302](https://github.com/GlennnM/FlashPrivateServer/assets/77952439/1fa3b571-579e-4d2f-9552-03e55a646d06)

**Comment by GlennnM** [comment] 2023-12-21 05:48
This is caused by nk changing the event ids which makes old guns associated with the wrong event(or in this case no event at all), if you download and run the newest client update(3.6) from releases it should be fixed

**Closed** 2023-12-25 00:13 UTC
